script - improve vpn-menu script

diff --git a/others/vpn-menu b/others/vpn-menu
--- a/others/vpn-menu
+++ b/others/vpn-menu
@@ -7,11 +7,10 @@ log() {
 }
 
 turn_off() {
-
     if [[ "$current_vpn" != "" ]]; then
         log "Turning off VPN interface $current_vpn"
 
-        wg-quick down $current_vpn
+        systemctl stop "wg-quick@$current_vpn"
     fi
 }
 
@@ -35,13 +34,28 @@ else
 
     select selection in $vpn_options
     do
-        turn_off
-
         selection=$(echo "$selection" | sd ".conf" "")
+
+        if [[ "$current_vpn" == "$selection" ]]; then
+            log "Already connected to VPN interface $selection"
+            exit 1
+        fi
+
+        turn_off
 
         log "Turning on VPN interface $selection"
 
-        sudo wg-quick up $selection
+        systemctl start "wg-quick@$selection"
+        if [[ "$?" != 0 ]]; then
+            interface=$(ip -o a | rg enp | sd '^.*(enp\ds\d).*' '$1')
+
+            log "File Exists error, flushing interface $interface"
+
+            ip addr flush "$interface"
+            systemctl start "wg-quick@$selection"
+
+            sleep 5
+        fi
 
         log "Done"
 
